AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:

  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: apoor-hello-bucket

  HelloReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: read_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref HelloBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref HelloBucket
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: post

  HelloScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: schedule_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - S3WritePolicy:
          BucketName: !Ref HelloBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref HelloBucket
      Events:
        ScheduledRead:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: HelloTestSamSchedule
            Enabled: True




Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for HelloReadFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HelloBucket:
    Description: "HelloBucket's ARN"
    Value: !GetAtt HelloBucket.Arn
