AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: apoor-hello-bucket

  HelloReadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: read_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref HelloBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref HelloBucket
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post

  HelloScheduleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: schedule_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - S3WritePolicy:
          BucketName: !Ref HelloBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref HelloBucket
      Events:
        ScheduledRead:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: HelloTestSamSchedule
            Enabled: True




Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HelloBucket:
    Description: "HelloBucket's ARN"
    Value: !GetAtt HelloBucket.Arn
